### ISSUE TITLE
Can't retrieve the infos for albums formed of only one song

### ISSUE THREAD

**Issue by Ramethep** [Otiel/BandcampDownloader#336]
Hello Otiel. Thank you very much for all the work on the new version.

Sadly, it seems not to work completely, yet. I'm getting the "could not retrieve album info" message for albums including only one song. 

Also, as it was the case before, i believe, when trying to dl a large discography, it only get the first 16 releases.

Again, thank you very much.

**Comment by SamuelBucher** [comment]
Seconding this. Same issue exists for [kameryn1811](https://github.com/kameryn1811)'s downloader.

**Comment by Otiel** [comment]
>I'm getting the "could not retrieve album info" message for albums including only one song.

Can you provide a example URL please?

>Also, as it was the case before, i believe, when trying to dl a large discography, it only get the first 16 releases.

Yes this is tracked in #252 and on the top of my todo list. 😃

**Comment by Ramethep** [comment]
> Can you provide a example URL please?

Yes. I was trying to dl this one: https://michaelplater.bandcamp.com/track/i-fell-in-love-with-the-stars-2

**Comment by OlegSuhih** [comment]
I get the error "Could not retrieve album info for..." again

**Comment by Otiel** [comment]
This should be fixed in [v1.5.1](https://github.com/Otiel/BandcampDownloader/releases/tag/v1.5.1)

**Comment by OlegSuhih** [comment]
Version v.1.5.1 runs on Windows 10 (Version 22H2). Thank you!

**Comment by Ramethep** [comment]
Thank you again

**Comment by bobbydriver** [comment]
Am on the new/latest version 1.5.1 and it's still not working on single track downloads (album downloads work)
eg
https://closelobstersmusic.bandcamp.com/track/firestation-towers

**Comment by Otiel** [comment]
@bobbydriver Thanks for the report, this should be fixed in [v1.5.2](https://github.com/Otiel/BandcampDownloader/releases/tag/v1.5.2)
