### ISSUE TITLE
Parsing error and crash for specific album

### ISSUE THREAD

**Issue by J4H7G** [Otiel/BandcampDownloader#341]
I'm trying to download: https://surgeryhead.bandcamp.com/album/the-petrified-tower
_This album has extremely long and unorthodox track names_

If I have concurrent download on it crashes. (1 album 10 tracks) 
```
System.IO.IOException The process cannot access the file because it is being used by another process.
```

If I try downloading the track that might have caused the error it doesn't crash, instead I get this
```
BandcampDownloader.Bandcamp.Download.AlbumInfoRetriever  Could not retrieve album info for https://surgeryhead.bandcamp.com/track/in-a-vampire-conquered-world-life-in-human-settlements-is-a-rough-game-you-are-mounting-a-heist-of-the-magical-scrolls-owned-by-the-literate-clerics-that-rule-your-fortress-township  System.FormatException: String '' was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.DateTime.Parse(String s)
   at BandcampDownloader.Bandcamp.Extraction.BandcampDateTimeJsonConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in D:\GitHub\BandcampDownloader\src\BandcampDownloader\Bandcamp\Extraction\BandcampDateTimeJsonConverter.cs:line 15
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at BandcampDownloader.Bandcamp.Extraction.AlbumInfoParser.GetAlbumInfoFromAlbumPage(String htmlContent, CancellationToken cancellationToken) in D:\GitHub\BandcampDownloader\src\BandcampDownloader\Bandcamp\Extraction\AlbumInfoParser.cs:line 49
   at BandcampDownloader.Bandcamp.Download.AlbumInfoRetriever.GetAlbumsAsync(IReadOnlyCollection`1 albumsUrls, CancellationToken cancellationToken) in D:\GitHub\BandcampDownloader\src\BandcampDownloader\Bandcamp\Download\AlbumInfoRetriever.cs:line 59

```

**Logs**
Concurrent download log:
https://github.com/user-attachments/files/23850796/BandcampDownloader.log
Single download log:
https://github.com/user-attachments/files/23850719/BandcampDownloader.log

**Comment by Otiel** [comment]
Thanks for the report.

Are you using a cloud storage (OneDrive, Dropbox, Nextcloud, Google Drive...) for the directory `D:\My Stuff\Music\Music Library\`?

**Comment by Otiel** [comment]
Your second issue is fixed in [v1.5.2](https://github.com/Otiel/BandcampDownloader/releases/tag/v1.5.2)

I'm still looking for the reason for the first issue, it is being tracked in #344

**Comment by J4H7G** [comment]
Firstly thank you so much for your dedication for this project!


> Thanks for the report.
> 
> Are you using a cloud storage (OneDrive, Dropbox, Nextcloud, Google Drive...) for the directory `D:\My Stuff\Music\Music Library\`?

I don't have any cloud storage linked to this directory. I thought it was my music player interfering somehow, so I restarted and the issue is still present. It only crashes when I have concurrent downloads on

**Comment by Otiel** [comment]
Thanks for the reply, that's helpful. 👍

I couldn't reproduce it yet, but I will keep looking.
